name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Build with Gradle
        env:
          KEY: ${{secrets.github_token}}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
        run: |
          chmod +x gradlew
#          ./gradlew test
          ./gradlew publish
#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v2
#        if: always()
#        with:
#          report_paths: '**/build/test-results/test/TEST-*.xml'
